spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plus
    username: ${username}
    password: ${password}

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    # show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
logging:
   level:
    org.hibernate.sql: debug
    org.hibernate.type: trace