spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/plus
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    # show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379

logging:
   level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  secret-key: cHRrUVFSclNhUVRTWmJ0R2hLY1VaLTE5ajIyVTFyZUcxU2ZuNFR1d1plVDVFZTItVzI1ZWZOU3Q4QTM=
  access-token-expiration: 86400000  #1시간
  refresh-token-expiration: 604800000 #하루
