spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/plus
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    # show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
logging:
   level:
    org.hibernate.sql: debug
    org.hibernate.type: trace